import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import Logged from "./logged";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {sessionData && (
          <button
            className="mt-4 rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20 md:absolute md:right-4"
            onClick={() => void signOut()}
          >
            Sign Out
          </button>
        )}
        <div className="container flex flex-col items-center justify-center gap-12 p-4 md:py-16 ">
        {!sessionData && <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">Log In</h1>}
          <div className="flex flex-col items-center gap-2 md:mt-8 w-full">
            {!sessionData && (
              <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={() => void signIn()}
              >
                Sign In
              </button>
            )}
            {sessionData && <Logged />}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;